<script src='//ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js'></script>
<script src='{$static_location}/js/jquery-ui-1.8.5.custom.min.js'></script>
<script src='{$static_location}/js/jquery.ct.js'></script>
<script src='{$static_location}/js/autoresize.jquery.min.js'></script>
<script src='{$static_location}/js/raphael.js'></script>
<script src='{$static_location}/js/main.js'></script>
<script src='{$static_location}/js/admin.js'></script>
<script src='//apis.google.com/js/plusone.js'></script>
<script src='//connect.facebook.net/en_US/all.js#appId={$facebook_app_id}&amp;xfbml=1'></script>
