CREATE TABLE `mt_entry` (
   `entry_id` int(11) not null auto_increment,
   `entry_blog_id` int(11) not null default '0',
   `entry_status` smallint(6) not null default '0',
   `entry_author_id` int(11) not null default '0',
   `entry_allow_comments` tinyint(4),
   `entry_allow_pings` tinyint(4),
   `entry_convert_breaks` varchar(30),
   `entry_category_id` int(11),
   `entry_title` varchar(255),
   `entry_excerpt` text,
   `entry_text` text,
   `entry_text_more` text,
   `entry_to_ping_urls` text,
   `entry_pinged_urls` text,
   `entry_keywords` text,
   `entry_tangent_cache` text,
   `entry_created_on` datetime,
   `entry_modified_on` timestamp default CURRENT_TIMESTAMP,
   `entry_created_by` int(11),
   `entry_modified_by` int(11),
   `entry_basename` varchar(255),
   `entry_atom_id` varchar(255),
   `entry_week_number` int(11),
   PRIMARY KEY (`entry_id`),
   KEY `entry_blog_id` (`entry_blog_id`),
   KEY `entry_status` (`entry_status`),
   KEY `entry_author_id` (`entry_author_id`),
   KEY `entry_created_on` (`entry_created_on`),
   KEY `entry_basename` (`entry_basename`),
   KEY `mt_entry_week_number` (`entry_week_number`),
   KEY `entry_keywords` (`entry_keywords`,`entry_title`,`entry_excerpt`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
